module.exports = [
  { name: "Product 1" },
  { name: "Product 2" },
  { name: "Product 3" },
  { name: "Product 4" },
  { name: "Product 5" },
  { name: "Product 6" },
  { name: "Product 7" },
  { name: "Product 8" },
  { name: "Product 9" },
  { name: "Product 10" },
  { name: "Product 11" },
  { name: "Product 12" },
  { name: "Product 13" },
  { name: "Product 14" },
  { name: "Product 15" },
  { name: "Product 16" },
  { name: "Product 17" },
  { name: "Product 18" },
  { name: "Product 19" },
  { name: "Product 20" },
  { name: "Product 21" },
  { name: "Product 22" },
  { name: "Product 23" },
];
